name: Test Github Actions Variables
on: issue_comment
env:
  TOP_LEVEL_ENV_VAR: this_is_a_top_level_var_of_a_workflow
jobs:
  test_vars:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print Reop Level Variable
        run: echo "${{ vars.TEST_REPO_LEVEL_VAR }}"
      - name: Print Environment Variable
        run: |
          echo "env var: ${{ vars.ENV_VAR }}"
          echo ""
          echo "action: ${{ github.action }}"
          echo "action_path: ${{ github.action_path }}"
          echo "action_ref: ${{ github.action_ref }}"
          echo "action_repository: ${{ github.action_repository }}"
          echo "action_status: ${{ github.action_status }}"
      - id: test-print-context
        name: Print Github Context
        run: |
          echo "action: ${{ github.action }}"
          echo "action_path: ${{ github.action_path }}"
          echo "action_ref: ${{ github.action_ref }}"
          echo "action_repository: ${{ github.action_repository }}"
          echo "action_status: ${{ github.action_status }}"
