name: Test Github Actions Variables
on: issue_comment
env:
  TOP_LEVEL_ENV_VAR: this_is_a_top_level_var_of_a_workflow
jobs:
  test_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print Reop Level Variable
        run: echo "${{ vars.TEST_VAR }}"
      - name: Print Env Variable
        run: echo "${{ vars.MINE_ENV_VARIABLE }}"
